#!/usr/bin/env python3
"""Render Mobile audience reading guide from editorial profiles and current facts.

Final location: knowledge/scripts/render_audiences.py
Uses only the Python standard library and never writes product facts.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def read_jsonl(path: Path) -> list[dict]:
    rows = []
    for line_no, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if line.strip():
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError as exc:
                raise ValueError(f"{path}:{line_no}: {exc}") from exc
    return rows


def index_files(paths: list[Path]) -> dict[str, dict]:
    result = {}
    for path in paths:
        for row in read_jsonl(path):
            rid = row["id"]
            if rid in result:
                raise ValueError(f"Duplicate ID: {rid}")
            result[rid] = row
    return result


def bullet_list(items: list[str]) -> list[str]:
    return [f"- {item}" for item in items]


def anchor(rid: str) -> str:
    return rid.lower()


def links(ids: list[str]) -> str:
    return "、".join(f"[{rid}](#{anchor(rid)})" for rid in ids) or "无"


def render(root: Path | None = None, audiences_dir: Path | None = None) -> Path:
    """Regenerate guide.md; optional paths support isolated staging checks."""
    knowledge_root = Path(root) if root is not None else ROOT
    audience_root = Path(audiences_dir) if audiences_dir is not None else knowledge_root / "audiences"
    profiles = read_jsonl(audience_root / "profiles.jsonl")
    facts = index_files(sorted((knowledge_root / "products").glob("*.facts.jsonl")))
    compatibility = index_files(sorted((knowledge_root / "compatibility").glob("*.jsonl")))
    sources = index_files(sorted((knowledge_root / "sources").glob("*.jsonl")))
    scenarios = index_files([knowledge_root / "scenarios" / "cards.jsonl"])
    models = index_files([knowledge_root / "products" / "models.jsonl"])
    records = {**facts, **compatibility}
    if set(facts).intersection(compatibility):
        raise ValueError("Product and compatibility IDs overlap")
    all_ids = [row["id"] for row in profiles]
    if len(all_ids) != len(set(all_ids)):
        raise ValueError("Duplicate audience ID")
    referenced = set()
    for row in profiles:
        rid = row["id"]
        if row["kind"] != "editorial_hypothesis" or row["status"] != "hypothesis_only":
            raise ValueError(f"{rid}: audience is not an editorial hypothesis")
        if row["basis"]["type"] != "editorial_reasoning" or row["basis"]["empirical_evidence_refs"]:
            raise ValueError(f"{rid}: empirical evidence must be handled separately")
        for fragment in row["natural_expression"]["illustrative_fragments"]:
            if (fragment["content_mode"] != "training_fiction"
                or fragment["calibration_status"] != "pending_calibration"
                or fragment["user_endorsed"] is not False
                or fragment["source_kind"] != "synthetic_illustration"
                or fragment["product_claims"]):
                raise ValueError(f"{rid}: illustrative fragment lost its training boundary")
        for key, catalog in (("fact_ids", facts), ("compatibility_ids", compatibility)):
            for record_id in row[key]:
                if record_id not in catalog or catalog[record_id]["status"] != "verified":
                    raise ValueError(f"{rid}: {record_id} missing or not verified")
                record = catalog[record_id]
                if record.get("support") == "unconfirmed":
                    raise ValueError(f"{rid}: {record_id} has unconfirmed support")
                for ref in record["source_refs"]:
                    if ref["source_id"] not in sources:
                        raise ValueError(f"{record_id}: unknown source {ref['source_id']}")
                referenced.add(record_id)
        for scene_id in row["scenario_ids"]:
            if scene_id not in scenarios:
                raise ValueError(f"{rid}: unknown scenario {scene_id}")

    lines = [
        "# Mobile 角色与使用心理",
        "",
        "<!-- Generated by scripts/render_audiences.py. Edit profiles.jsonl; do not maintain this file separately. -->",
        "",
        f"本页包含 {len(profiles)} 类编辑角色假设。维护源是 [profiles.jsonl](profiles.jsonl)，字段约定见 [SCHEMA.md](SCHEMA.md)。这些角色可以重叠、随任务变化；排序不代表市场大小、优先级或出现频率。没有真实调研、人群占比或心理诊断依据。",
        "",
        "**培训用假想消费者草稿**：本页口语片段统一为 `training_fiction`、`pending_calibration`，未获用户认可，不是真实消费者原话、实测反馈或可直接套用的成品评论。",
        "",
        "## 使用方式",
        "",
        "先读本节和角色索引，再按当前任务选择相关 1—3 类；可按角色关键词或完整编号定位。只有要使用某条产品能力时才读取对应依据与完整条件，无需每次读完全部角色及事实附录。",
        "",
        "从当前任务进入：要留住什么画面 → 为什么在意 → 愿意承担哪些操作 → 何时会停止或换办法。角色名称只是检索入口；先看任务线索，再选择一种可能动机，不从身份推断必然心理。",
        "",
        "把四层分开：场景需求描述要完成的事；心理动机解释这件事可能为什么重要；顾虑指出具体条件下的取舍；自然说法通过动作、注意力或比较表现它。不要把分析术语塞进人物口中，也不要让每个人都从痛点、焦虑或后悔开场。",
        "",
        "“麻烦”可能分别指携带、步骤、反复确认、打断同行或错过片刻。用具体线索判断，不能看到同一个词就套同一种故事。固定机位、请人帮助、用现有设备、暂时不拍和不升级都可以是合理结果。",
        "",
        "角色及片段不建立产品事实。下方可用事实只是查证入口；每条引用是独立能力路径，不证明这些配件或功能可以同时组合。引用时读取完整记录，保留型号、组件、手机、App、系统、固件和场地条件。场景记录同样是编辑解释。",
        "",
        "实际评论、回复或批次写作由调用项目的共享写手入口处理。本页只提供选材与表达观察，不替代数量、互动、格式、去重和校准流程；训练人物和用户纠偏不直接写成产品能力。",
        "",
        "## 角色索引",
        "",
    ]
    for row in profiles:
        lines.append(f"- [{row['id']}｜{row['role']}](#{anchor(row['id'])})：{row['task']}")
    lines += ["", "## 角色记录", ""]
    for row in profiles:
        expression = row["natural_expression"]
        load = row["acceptable_operation_load"]
        lines += [
            f'<a id="{anchor(row["id"])}"></a>',
            "",
            f"### {row['id']}｜{row['role']}",
            "",
            "`editorial_hypothesis` · `hypothesis_only`",
            "",
            f"**任务**：{row['task']}。",
            "",
            "**可能动机**：" + "；".join(row["possible_motives"]) + "。",
            "",
            f"**心理取舍**：{row['psychological_tension']}。",
            "",
            "**可接受操作负担**：" + "；".join(load["willing_to_do"]) + "。" + load["threshold"] + "。",
            "",
            "**放弃或换办法的触发**：" + "；".join(row["abandon_or_switch_triggers"]) + "。",
            "",
            "**替代解释**：" + "；".join(row["alternative_explanations"]) + "。",
            "",
            "**适用线索**：" + "；".join(row["selection_cues"]) + "。",
            "",
            f"**自然表达方向**：注意力放在{expression['attention_focus']}。{expression['expression_mechanism']}。",
            "",
            "**易误判的写法**：" + "；".join(expression["avoid_patterns"]) + "。",
            "",
        ]
        for fragment in expression["illustrative_fragments"]:
            lines += [
                f"> {fragment['text']}",
                "",
                f"片段设定：{fragment['persona_context']}。状态：`training_fiction`／`pending_calibration`／`user_endorsed=false`，不含产品能力结论。",
                "",
            ]
        lines += [
            "**能力边界**：" + "；".join(row["claim_guardrails"]) + "。",
            "",
            "**可用产品事实**：" + links(row["fact_ids"]) + "。",
            "",
            "**可用兼容记录**：" + links(row["compatibility_ids"]) + "。",
            "",
            "**关联场景**：" + "、".join(f"{sid}（{scenarios[sid]['title']}）" for sid in row["scenario_ids"]) + "。",
            "",
            row["model_scope_note"],
            "",
        ]
    lines += [
        "## 引用依据与完整条件",
        "",
        f"以下 {len(referenced)} 条记录从事实源自动读取并去重，每条在生成时均为 `verified`。此状态仅表示记录核验日期读过官方资料，不表示实机测试、角色偏好或永久兼容。核验日期属于产品证据，角色记录日期不刷新它。",
        "",
        "产品能力取自产品／兼容 JSONL；本区是生成阅读版。官方原件、定位与哈希在 sources 台账保存。角色之间的关联不创造新兼容结论。",
        "",
    ]
    for rid in sorted(referenced):
        record = records[rid]
        model_names = "、".join(models[mid]["official_name"] for mid in record["models"])
        lines += [
            f'<a id="{anchor(rid)}"></a>',
            "",
            f"### {rid}",
            "",
            f"型号：{model_names}。组件：{record['component']}。状态：`{record['status']}`。实际核验：{record['checked_at']}。",
            "",
            record["statement"],
            "",
        ]
        if rid in compatibility:
            lines += [
                f"兼容路径：{record['method']}。设备：{'、'.join(record['devices'])}。支持口径：`{record['support']}`。功能：{'、'.join(record['features'])}。",
                "",
            ]
        lines += ["条件：", ""]
        lines += bullet_list(record["conditions"]) if record["conditions"] else ["- 本条没有额外列出条件；这不消除其他组合记录的限制。"]
        lines += ["", "限制与不可推论：", ""]
        lines += bullet_list(record["limitations"]) if record["limitations"] else ["- 本条没有额外列出限制；不能据此外推未列能力。"]
        lines += ["", "官方依据：", ""]
        for ref in record["source_refs"]:
            source = sources[ref["source_id"]]
            lines.append(f"- {ref['source_id']}｜{ref['locator']}；[{source['title']}](<{source['url']}>)。")
        lines.append("")
    output = audience_root / "guide.md"
    output.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return output


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--audiences-dir", type=Path)
    args = parser.parse_args()
    print(render(args.root, args.audiences_dir))
